# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test4.py
# Created on: 2016-11-07 11:32:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput=True

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
NHLDandBuffLakes_Original = "G:\\NHLD\\GIS_DATA\\NHLD_GIS_Data_FINAL\\NHLDandBuffLakes\\NHLDandBuffLakes_Original_ZJH_Rev1.shp"
NHLDandBuffLakes_Rev1_shp_mod = "G:\\NHLD\\GIS_DATA\\NHLD_GIS_Data_FINAL\\NHLDandBuffLakes\\NHLDandBuffLakes_Rev1.shp"


# Process: Copy Features
arcpy.CopyFeatures_management(NHLDandBuffLakes_Original, NHLDandBuffLakes_Rev1_shp_mod, "", "0", "0", "0")

# Process: Add Field
arcpy.AddField_management(NHLDandBuffLakes_Rev1_shp_mod, "Perim_m_0", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(NHLDandBuffLakes_Rev1_shp_mod, "Area_m2_0", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(NHLDandBuffLakes_Rev1_shp_mod, "WALA_0", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(NHLDandBuffLakes_Rev1_shp_mod, "Perim_m_0", "[Perimeter]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(NHLDandBuffLakes_Rev1_shp_mod, "Area_m2_0", "[Area_m2]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(NHLDandBuffLakes_Rev1_shp_mod, "WALA_0", "[WALA]", "VB", "")

# Process: Delete Field
arcpy.DeleteField_management(NHLDandBuffLakes_Rev1_shp_mod, "AreaSqKm;Shape_Leng;Shape_Area;NHLD_lakes;Perimeter;OBJECTID;Permanent1;GNIS_ID_1;Area_m2;WALA")

#NHLDandBuffLakes_Rev2.shp added with ModifyRev1LakeShpFile_Add_PNFHUC12  PNF_HUC12 field

